### ISSUE TITLE
Allow Seed spec and Silo URLs to be configurable at runtime.

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed-vault#3]
Presently you have to rebuild the entire project with the proper endpoint configs. We deploy in a number of different environments and this is not optimal. I'd like to just provide a JSON file with the proper overrides to allow me to deploy and only change those member values. Since this is built as a static website and often deployed into an S3 bucket, environment variables will not work.

**Comment by mheppner** [comment]
https://github.com/ngageoint/seed-vault/blob/389c35b1bbf57aa0182de756f784e6563a4f2fc7/src/app/app.component.ts#L14

**Comment by mheppner** [comment]
An empty JSON file is already provided (`/assets/appConfig.json`) and will override anything set in [`src/environments/environment.*.ts`](https://github.com/ngageoint/seed-vault/tree/master/src/environments).

Eg, to change only the seed spec url, your appConfig.json should look like this:

```
{
    "seedSpecUrl": "http://google.com"
}
```
